/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculator;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SumCalculatorTest {
    private SumCalculator calc;

    @BeforeEach
    public void beforeEach() {
        calc = new SumCalculator();
    }

    @Test
    public void testThatSumWorksCorrect() {
        int actual = calc.sum(1);
        int expected = 1;
        Assertions.assertEquals(expected,actual);
    }

    @Test
    public void testThatSumWorksCorrect2() {
        int actual = calc.sum(3);
        int expected = 6;
        Assertions.assertEquals(expected,actual);
    }

    @Test
    public void testThatExceptionWorksCorrect() {
        Assertions.assertThrows(IllegalArgumentException.class,() -> calc.sum(0));
    }
}
