/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculator;

public class SumCalculator {
    public int sum(int n) {
        int sum =0;
        if(n>0){
            sum =((1+n)*n)/2;
        } else {
            throw new IllegalArgumentException("Необхідно ввести число більше 0!");
        }
        return sum;
    }
}

